// Generated by CoffeeScript 1.10.0
(function() {
  var slice = [].slice;

  $("#click").on("click", function() {
    var awardMedals, contenders, gold, rest, silver;
    alert("Hello!");
    gold = silver = rest = "unknown";
    awardMedals = function() {
      var first, others, second;
      first = arguments[0], second = arguments[1], others = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    };
    gold = first;
    silver = second;
    rest = others;
    contenders = ["Micheal Phelps", "Lia Xiang", "Yao Ming", "Allyson Felix", "Shawn Johnson"];
    awardMedals.apply(null, contenders);
    $("#medal").on("click", function() {
      alert("Gold:" + gold);
      alert("Silver" + silver);
      return alert("The Field:" + rest);
    });
    return $("#count").on("click", function() {
      var countdown, num;
      countdown = (function() {
        var i, results;
        results = [];
        for (num = i = 10; i >= 1; num = --i) {
          results.push(num);
        }
        return results;
      })();
      return alert(countdown);
    });
  });

}).call(this);
